"""Extract release notes from a semantic-release dry-run log file.

Reads release.log and writes the release notes section (generated by
@semantic-release/release-notes-generator) to release-notes.md.
"""

import itertools
import re
import sys

LOG_FILE = "release.log"
OUTPUT_FILE = "release-notes.md"

# semantic-release info log lines contain this prefix sequence (U+203A U+2139)
INFO_MARKER = "\u203a \u2139"
NOTES_HEADER = "Release note for version"


def extract_notes(log_lines: list[str]) -> str:
    start = next(
        (i for i, line in enumerate(log_lines) if NOTES_HEADER in line), None
    )
    if start is None:
        return ""
    note_lines = list(
        itertools.takewhile(lambda l: INFO_MARKER in l, log_lines[start + 1 :])
    )
    notes = [
        re.sub(f"^.*?{re.escape(INFO_MARKER)}  ", "", line.rstrip("\n")).rstrip()
        for line in note_lines
    ]
    return "\n".join(notes)


if __name__ == "__main__":
    try:
        with open(LOG_FILE) as f:
            log_lines = f.readlines()
    except OSError as e:
        print(f"Error reading {LOG_FILE}: {e}", file=sys.stderr)
        sys.exit(1)

    notes = extract_notes(log_lines)

    with open(OUTPUT_FILE, "w") as f:
        f.write(notes)
