version: "3.8"
services:
  mysql:
    command: >
      mysqld --character-set-server=utf8mb4
             --collation-server=utf8mb4_unicode_ci
             --default-authentication-plugin=mysql_native_password
             --max_allowed_packet=100M
             --lower_case_table_names=1
             --sql-mode=""
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    environment:
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=${MYSQL_USER}
    healthcheck:
      test: /usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute 'SELECT 1;' --silent 2> /dev/null || exit 1
    image: mysql:${MYSQL_VERSION}
    mem_limit: 1g
    ports:
      - "${MYSQL_PORT}:3306"
    restart: unless-stopped
    volumes:
      - data-mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOSTS=mysql
      - UPLOAD_LIMIT=200M
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    mem_limit: 256m
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: unless-stopped
volumes:
  data-mysql:
