name: Node CI

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install and Build
      run: |
        yarn
        yarn build:prod
